---
- name: Install Cadvisor
  hosts: production
  become: true

  tasks:
    - name: Run cAdvisor container
      community.docker.docker_container:
        name: cadvisor
        image: gcr.io/cadvisor/cadvisor:{{ cadvisor_version }}
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:ro"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
        networks:
          - name: monitoring
        state: started
