---
- name: Run cAdvisor container
  community.docker.docker_container:
    name: '{{ docker_prefix }}-cadvisor'
    image: gcr.io/cadvisor/cadvisor:{{ cadvisor_version }}
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - name: '{{ docker_network_name }}'
    state: started
